CREATE TABLE `invest_scheme_details` (
  `id` int(11) NOT NULL,
  `Vendor_ID` int(11) NOT NULL,
  `Scheme_Name` varchar(40) NOT NULL,
  `Min_Inv_Amount` int(10) NOT NULL,
  `Max_Inv_Amount` int(20) NOT NULL,
  `Aggregate_Amount` int(10) NOT NULL,
  `Lockin` tinyint(1) NOT NULL COMMENT '1=Yes| 0=No',
  `Cooling_Period` int(10) NOT NULL,
  `Interest_Rate` decimal(5,0) NOT NULL,
  `hike_rate` decimal(10,0) NOT NULL,
  `Interest_Type` varchar(40) NOT NULL,
  `Withrawl_Anytime` tinyint(1) NOT NULL COMMENT '1=Yes| 0=No',
  `Pre_Mat_Rate` decimal(5,0) NOT NULL,
  `Lockin_Period` int(10) NOT NULL,
  `Tenure` int(10) NOT NULL,
  `Auto_Redeem` tinyint(1) NOT NULL COMMENT '1=Yes| 0=No',
  `status` int(11) NOT NULL COMMENT '1=Active, 0=In-Active',
  `updated_on` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `created_date` datetime NOT NULL DEFAULT current_timestamp(),
  `payout_type` enum('monthly','maturity') DEFAULT NULL,
  `scheme_descripiton` varchar(800) DEFAULT NULL,
  `lender_management_fee_percentage` int(12) DEFAULT NULL COMMENT 'added this field on 2024-september-05',
  `lender_management_fee_rupee` int(12) DEFAULT NULL COMMENT 'added this field on 2024-september-05',
  `type_of_lender_management_fee` varchar(60) DEFAULT NULL COMMENT 'added this field on 2024-september-05',
  `step_up_value` varchar(5) DEFAULT NULL,
  `diversification_factor_value` varchar(5) DEFAULT NULL,
  `minimum_loan_amount` varchar(5) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
